In [1]:
import numpy as np

In [3]:
ar1=np.array([1,2,3,4,5])
print(ar1)
print(type(ar1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
li1=[5,10,15]
li2=[2,4,19]
li3=[12,1,3]
ark=np.array([li1,li2,li3])
print(ark)

[[ 5 10 15]
 [ 2  4 19]
 [12  1  3]]


In [9]:
print(ark[0,0])

5


In [11]:
new_way=np.arange(2,19,3)
print(new_way)

[ 2  5  8 11 14 17]


In [13]:
another_alternative=np.linspace(0,1,5)
print(another_alternative)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
print(new_way.shape)

(6,)


In [17]:
ark1=ark[0:2,]
print(ark1)

[[ 5 10 15]
 [ 2  4 19]]


In [19]:
print(ark1.shape)

(2, 3)


In [25]:
xy=ark1.reshape(3,2)
print(ark1.reshape(3,2))
print()
print()
print(xy)
print(type(xy))

[[ 5 10]
 [15  2]
 [ 4 19]]


[[ 5 10]
 [15  2]
 [ 4 19]]
<class 'numpy.ndarray'>
